stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PLATFORMS: linux/amd64

.container-build-pre-script: &container-build-pre-script |
  set -x
  apk add --no-cache img
  img login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

.declare-extra-destinations: &declare-extra-destinations |
  if [[ ! "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]] && [[ -z "$CI_COMMIT_TAG" ]]; then
    export BRANCH_NAME="-$CI_COMMIT_BRANCH"
  fi

  export BASE_TAG=$(date --date="${CI_COMMIT_TIMESTAMP//[T+]/ }" '+%Y.%m.%d.%H%M')
  if [[ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]]; then
    export CONTAINER_EXTRA_DESTINATION="-t $CI_REGISTRY_IMAGE:latest$BRANCH_NAME"
  fi
  if [ -n "$CI_COMMIT_TAG" ]; then
    export BRANCH_NAME=""
    export IMAGE_TAG="$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    export CONTAINER_EXTRA_ARGS="--build-arg BASE_IMAGE=$IMAGE_TAG"
    export CONTAINER_EXTRA_DESTINATION="-t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  fi

.build: &build |
  img build \
    -f $CI_PROJECT_DIR/Dockerfile \
    $CONTAINER_EXTRA_DESTINATION \
    -t $CI_REGISTRY_IMAGE:$BASE_TAG$BRANCH_NAME \
    --platform $PLATFORMS \
    $CI_PROJECT_DIR

build:
  stage: build
  timeout: 5h
  image:
    name: docker.io/alpine:3.14
    entrypoint: [""]
  retry: 2
  before_script:
    - *container-build-pre-script
    - *declare-extra-destinations
  script:
    - *build
