stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PLATFORMS: linux/amd64,linux/arm64

# Kaniko
.registry-login: &registry-login |
  set -x
  cat << EOF > /kaniko/.docker/config.json
  {
    "auths":{
      "$CI_REGISTRY": {
        "username":"$CI_REGISTRY_USER",
        "password":"$CI_REGISTRY_PASSWORD"
      }
    }
  }
  EOF

.declare-extra-destinations: &declare-extra-destinations |
  if [[ ! "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]] && [[ -z "$CI_COMMIT_TAG" ]]; then
    export BRANCH_NAME="-$CI_COMMIT_BRANCH"
  fi

  export BASE_TAG=$(date --date="${CI_COMMIT_TIMESTAMP//[T+]/ }" '+%Y.%m.%d.%H%M')
  if [[ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]]; then
    export KANIKO_EXTRA_DESTINATION="--destination $CI_REGISTRY_IMAGE:latest$BRANCH_NAME"
  fi
  if [ -n "$CI_COMMIT_TAG" ]; then
    export BRANCH_NAME=""
    export IMAGE_TAG="$CI_REGISTRY_IMAGE/humacs:$CI_COMMIT_TAG"
    export KANIKO_EXTRA_DESTINATION="--destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  fi

.build: &build |
  /kaniko/executor \
    --snapshotMode=redo \
    --cache=false \
    --context $CI_PROJECT_DIR \
    --dockerfile $CI_PROJECT_DIR/Dockerfile \
    --destination $CI_REGISTRY_IMAGE:$BASE_TAG$BRANCH_NAME \
    $KANIKO_EXTRA_ARGS \
    $KANIKO_EXTRA_DESTINATION

# Img
.container-build-pre-script: &container-build-pre-script |
  set -x
  apk add --no-cache img
  img login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

.declare-extra-destinations: &declare-extra-destinations |
  if [[ ! "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]] && [[ -z "$CI_COMMIT_TAG" ]]; then
    export BRANCH_NAME="-$CI_COMMIT_BRANCH"
  fi

  export BASE_TAG=$(date --date="${CI_COMMIT_TIMESTAMP//[T+]/ }" '+%Y.%m.%d.%H%M')
  if [[ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]]; then
    export CONTAINER_EXTRA_DESTINATION="-t $CI_REGISTRY_IMAGE/${APP}:latest$BRANCH_NAME"
  fi
  if [ -n "$CI_COMMIT_TAG" ]; then
    export BRANCH_NAME=""
    export IMAGE_TAG="$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG/${APP}"
    export CONTAINER_EXTRA_DESTINATION="-t $CI_REGISTRY_IMAGE/${APP}:$CI_COMMIT_TAG"
  fi

.build: &build |
  img build \
    -f $CI_PROJECT_DIR/${APP}.Dockerfile \
    $CONTAINER_EXTRA_DESTINATION \
    -t $CI_REGISTRY_IMAGE/${APP}:$BASE_TAG$BRANCH_NAME \
    --platform $PLATFORMS \
    $CI_PROJECT_DIR

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug-v1.3.0
    entrypoint: [""]
  retry: 2
  before_script:
    - *registry-login
    - *declare-extra-destinations
  script:
    - *build

build-exporter:
  stage: build
  timeout: 5h
  image:
    name: docker.io/alpine:3.14
    entrypoint: [""]
  variables:
    APP: exporter
  retry: 2
  before_script:
    - *container-build-pre-script
    - *declare-extra-destinations
  script:
    - *build

build-exposer:
  stage: build
  timeout: 5h
  image:
    name: docker.io/alpine:3.14
    entrypoint: [""]
  variables:
    APP: exposer
  retry: 2
  before_script:
    - *container-build-pre-script
    - *declare-extra-destinations
  script:
    - *build
