stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.registry-login: &registry-login |
  set -x
  cat << EOF > /kaniko/.docker/config.json
  {
    "auths":{
      "$CI_REGISTRY": {
        "username":"$CI_REGISTRY_USER",
        "password":"$CI_REGISTRY_PASSWORD"
      }
    }
  }
  EOF

.declare-extra-destinations: &declare-extra-destinations |
  if [[ ! "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]] && [[ -z "$CI_COMMIT_TAG" ]]; then
    export BRANCH_NAME="-$CI_COMMIT_BRANCH"
  fi

  export BASE_TAG=$(date --date="${CI_COMMIT_TIMESTAMP//[T+]/ }" '+%Y.%m.%d.%H%M')
  if [[ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]]; then
    export KANIKO_EXTRA_DESTINATION="--destination $CI_REGISTRY_IMAGE:latest$BRANCH_NAME"
  fi
  if [ -n "$CI_COMMIT_TAG" ]; then
    export BRANCH_NAME=""
    export IMAGE_TAG="$CI_REGISTRY_IMAGE/humacs:$CI_COMMIT_TAG"
    export KANIKO_EXTRA_ARGS="--build-arg BASE_IMAGE=$IMAGE_TAG"
    export KANIKO_EXTRA_DESTINATION="--destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  fi

.build: &build |
  /kaniko/executor \
    --snapshotMode=redo \
    --cache=false \
    --context $CI_PROJECT_DIR \
    --dockerfile $CI_PROJECT_DIR/Dockerfile \
    --destination $CI_REGISTRY_IMAGE:$BASE_TAG$BRANCH_NAME \
    $KANIKO_EXTRA_ARGS \
    $KANIKO_EXTRA_DESTINATION

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug-v1.3.0
    entrypoint: [""]
  retry: 2
  before_script:
    - *registry-login
    - *declare-extra-destinations
  script:
    - *build
