# Deployment example
# Note that when running in Kubernetes, the field =shareProcessNamespace= in =v1.Pod.Spec= must be set to =true=.


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: environment-dev
  namespace: default
spec:
  serviceName: environment-dev
  replicas: 1
  selector:
    matchLabels:
      app: environment-dev
  template:
    metadata:
      labels:
        app: environment-dev
    spec:
      shareProcessNamespace: true
      containers:
        - name: environment
          image: registry.gitlab.com/sharingio/environment:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: home-ii
              mountPath: /home/ii
            - name: podlabels
              mountPath: /etc/podlabels
          command:
            - sleep
            - +Inf
        - name: environment-exporter
          image: registry.gitlab.com/sharingio/environment/exporter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 10093
          volumeMounts:
            - name: podlabels
              mountPath: /etc/podlabels
      volumes:
      - name: home-ii
        hostPath:
          path: /home/ii
      - name: podlabels
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
